language: node_js
node_js:
  - '12'
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" -password-stdin
  - docker build -t yd1340794/vue-ts:latest
  - docker push yd1340794/vue-ts:latest
