language: node_js
node_js:
  - '12'
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker image build -t vue-ts:latest
  - docker image push "$DOCKER_USERNAME"/vue-ts:latest
